name: payment_gateways_template
description: "Template for payment gateways."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  dartz: ^0.10.1
  go_router: ^15.1.0
  esewa_flutter_sdk:
    path: ./external_sdk/esewa_flutter_sdk
  flutter_dotenv: ^5.2.1
  khalti_flutter: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/logos/brand.png'
  adaptive_icon_foreground: 'assets/logos/brand.png'
  adaptive_icon_background: '#ffffff'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logos/
    - lib/core/data/sources/products.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
